{
  "formatVersion": "1.1",
  "component": {
    "group": "lol.osm",
    "module": "cantino",
    "version": "0.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "cantino-0.3.0.aar",
          "url": "cantino-0.3.0.aar",
          "size": 3628757,
          "sha512": "1927324e4da9845511fe0a41db0c3dc12f905d807d4b69d4b841959d48f709eb4bfb3b8947312ee99a6d16f0c6ac4c466baa47919604ef9282b4fae4009eefeb",
          "sha256": "54dbddb155aaf3e6e1a71386286ea115ea154e56f3331f8e22fdcd9deec36752",
          "sha1": "5575750248a7ed068eb357a8fd3bb081064607f0",
          "md5": "12438d5a4ecd183fff35e46123a17656"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "cantino-0.3.0.aar",
          "url": "cantino-0.3.0.aar",
          "size": 3628757,
          "sha512": "1927324e4da9845511fe0a41db0c3dc12f905d807d4b69d4b841959d48f709eb4bfb3b8947312ee99a6d16f0c6ac4c466baa47919604ef9282b4fae4009eefeb",
          "sha256": "54dbddb155aaf3e6e1a71386286ea115ea154e56f3331f8e22fdcd9deec36752",
          "sha1": "5575750248a7ed068eb357a8fd3bb081064607f0",
          "md5": "12438d5a4ecd183fff35e46123a17656"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cantino-0.3.0-sources.jar",
          "url": "cantino-0.3.0-sources.jar",
          "size": 53693,
          "sha512": "07bf9dd54ca16e7cf0e579aea3f4c60269af22199b4626d4563f562b749a036d7180c8bd352747e605561f0af3d943d7817a77fac051aabd6506137109939f37",
          "sha256": "9cab27198a047dab2bdd4062868133fe0a6fdd001af66f12e99f0cd79885e1eb",
          "sha1": "323a6d2644b5efc5d2a29b5b124dd025776fdde0",
          "md5": "c470dd53c2d5a04ba26cb2bd3e5b773e"
        }
      ]
    }
  ]
}
