package lol.osm.cantino

import android.util.Log
import androidx.test.ext.junit.runners.AndroidJUnit4
import androidx.test.platform.app.InstrumentationRegistry
import org.json.JSONArray
import org.json.JSONObject
import org.junit.Assert.assertEquals
import org.junit.Assert.fail
import org.junit.Test
import org.junit.runner.RunWith
import java.io.File

/**
 * Kotlin runner of the cross-platform parity corpus (tests/parity/README.md).
 *
 * Runs every non-`abi_only` call of tests/parity/calls.json in order through
 * the Kotlin API, maps results and typed [CantinoException]s into the canonical
 * form ([Canonical]) and compares each call's line byte for byte with
 * tests/parity/expected.json (generated by the Rust runner from the C ABI; this
 * test never writes it).
 *
 * Public API is used wherever it exists: [OsmStore] (import, open, get, query,
 * wayCoordinates, representativePoint) and [PmtilesInfo.read]. Without a public
 * equivalent it goes to the internal layer the AreaManager itself uses:
 * [SliceProtocol] for the slice helpers, and [NativeBridge] for the basemap
 * plan/assembler (the public path, [BasemapExtract.run], does its own HTTP and
 * cannot be fed canned bytes). [AsyncOsmStore] is not used: the corpus' wrong-thread
 * call needs the thread-confined synchronous store (README, "WrongThread"), and
 * every other call must run on the thread that opened the area.
 */
@RunWith(AndroidJUnit4::class)
class ParityTest {
    private val context = InstrumentationRegistry.getInstrumentation().context
    private val target = InstrumentationRegistry.getInstrumentation().targetContext

    private lateinit var scratch: File
    private lateinit var repo: File
    private val areas = HashMap<String, OsmStore>()

    @Test
    fun corpusMatchesCAbiByteForByte() {
        val root = File(target.cacheDir, "parity-${System.nanoTime()}").apply { mkdirs() }
        scratch = File(root, "scratch").apply { mkdirs() }
        repo = File(root, "repo").apply { mkdirs() }

        val calls = JSONArray(asset("calls.json").decodeToString())
        val expected = expectedLines(asset("expected.json").decodeToString())

        val results = ArrayList<Pair<String, String>>() // id to canonical line
        val ran = LinkedHashMap<String, Int>()
        val skipped = LinkedHashMap<String, Int>()
        try {
            for (index in 0 until calls.length()) {
                val call = calls.getJSONObject(index)
                val id = call.getString("id")
                val op = call.getString("op")
                if (call.optBoolean("abi_only", false)) {
                    skipped.merge(op, 1, Int::plus)
                    continue
                }
                ran.merge(op, 1, Int::plus)
                val result = try {
                    run(op, call.getJSONObject("args"))
                } catch (e: Throwable) {
                    // Not a typed CantinoException: a harness or adapter bug. Recorded as a
                    // mismatch for this call; the rest of the corpus still runs.
                    mapOf("harness_error" to "${e::class.java.name}: ${e.message}")
                }
                results += id to Canonical.write(mapOf("id" to id, "result" to result))
            }
        } finally {
            areas.values.forEach { runCatching { it.close() } }
            areas.clear()
        }

        val summary = "parity: ${ran.values.sum()} calls run, ${skipped.values.sum()} skipped (abi_only); run=$ran skipped=$skipped"
        Log.i(TAG, summary)
        println(summary)

        val actualText = resultFile(results.map { it.second })
        File(root, "actual.json").writeText(actualText)

        val mismatches = StringBuilder()
        var count = 0
        for ((id, line) in results) {
            val want = expected[id] ?: error("call $id missing from expected.json")
            if (line != want) {
                count++
                mismatches.append("MISMATCH $id\n  expected: $want\n  actual:   $line\n")
            }
        }
        if (count > 0) fail("$count of ${results.size} parity calls differ ($summary)\n$mismatches")

        // Every expected line not skipped as abi_only must have been produced, and the whole
        // result file must equal expected.json minus the abi_only lines.
        val ids = results.map { it.first }.toSet()
        val abiOnly = (0 until calls.length()).map { calls.getJSONObject(it) }
            .filter { it.optBoolean("abi_only", false) }.map { it.getString("id") }.toSet()
        assertEquals(expected.keys - abiOnly, ids)
        assertEquals(resultFile(expected.filterKeys { it !in abiOnly }.values.toList()), actualText)
    }

    @Test
    fun canonicalFormFollowsTheReadme() {
        // Code point order, not UTF-16 order: U+1F600 sorts after U+FF5A.
        assertEquals("""{"é":1,"ｚ":2,"😀":3}""", Canonical.write(mapOf("😀" to 3, "ｚ" to 2, "é" to 1)))
        // Minimal escaping: `/` and non-ASCII raw, control characters as lowercase \u00xx.
        assertEquals("\"a/b é \\\"q\\\" \\\\ \\n\\t\\b\\f\\r \\u0001\\u001f\"", Canonical.write("a/b é \"q\" \\ \n\t\b\u000c\r \u0001\u001f"))
        // Floats: shortest round-trip, always with a fraction, plain notation.
        assertEquals(
            listOf("1.0", "0.25", "-112.09", "12.0", "0.3333333333333333", "0.0001", "100.0", "10000000.0", "-112.0774999"),
            listOf(1.0, 0.25, -112.09, 12.0, 1.0 / 3.0, 1e-4, 100.0, 1e7, -112.0774999).map(Canonical::float),
        )
        assertEquals("[null,true,9223372036854775807,4294967295]", Canonical.write(listOf(null, true, Long.MAX_VALUE, 4294967295L)))
    }

    // ---- ops ----------------------------------------------------------------------------

    private fun run(op: String, args: JSONObject): Any? = when (op) {
        "import" -> outcome {
            val options = args.optJSONObject("options")?.let {
                ImportOptions(
                    preserveUntaggedMetadata = it.optBoolean("preserve_untagged_metadata", false),
                    cacheMiB = it.optInt("cache_mb", 16),
                )
            } ?: ImportOptions()
            val report = OsmStore.importArea(path(args.getString("input")), path(args.getString("destination")), options)
            // database_bytes is dropped from the canonical report (README, "two deliberate projections").
            mapOf("counts" to mapOf("nodes" to report.counts.nodes, "relations" to report.counts.relations, "ways" to report.counts.ways))
        }
        "open" -> outcome {
            areas[args.getString("area")] = OsmStore.open(path(args.getString("path")))
            null
        }
        "close" -> outcome {
            areas.remove(args.getString("area"))!!.close()
            null
        }
        "get" -> outcome(missingOnNull = true) { store(args).get(osmId(args))?.let(::tree) }
        "get_from_other_thread" -> outcome {
            val store = store(args)
            val id = osmId(args)
            var failure: Throwable? = null
            Thread { try { store.get(id) } catch (e: Throwable) { failure = e } }.apply { start(); join() }
            failure?.let { throw it }
            "no error"
        }
        "get_many" -> outcome {
            val ids = if (args.has("repeat")) {
                val repeat = args.getJSONObject("repeat")
                List(repeat.getInt("count")) { osmIdOf(repeat.getJSONObject("id")) }
            } else {
                args.getJSONArray("request").let { list -> List(list.length()) { osmIdOf(list.getJSONObject(it)) } }
            }
            store(args).get(ids).map { it?.let(::tree) }
        }
        "query" -> outcome { store(args).query(query(args.getJSONObject("request"))).map(::tree) }
        "way_coordinates" -> outcome(missingOnNull = true) {
            store(args).wayCoordinates(args.getLong("id"))?.flatMap { c -> listOf(c?.latE7, c?.lonE7) }
        }
        "representative_point" -> outcome(missingOnNull = true) {
            store(args).representativePoint(osmId(args))?.let { mapOf("lat_e7" to it.latE7, "lon_e7" to it.lonE7) }
        }
        "slice_job_request" -> outcome {
            val request = SliceProtocol.jobRequest(baseOf(args), bbox(args.getJSONObject("bbox")), args.getString("name"))
            mapOf("body" to request.body, "url" to request.url)
        }
        "slice_job" -> outcome {
            val job = SliceProtocol.job(baseOf(args), args.getString("response"))
            mapOf("download_url" to job.downloadUrl, "job_id" to job.id, "status_url" to job.statusUrl)
        }
        "slice_progress" -> outcome {
            val progress = SliceProtocol.progress(args.getString("status"))
            mapOf(
                "complete" to progress.complete,
                "fraction" to progress.fraction,
                "size_bytes" to progress.sizeBytes,
                "timestamp" to progress.timestamp,
            )
        }
        "basemap_info" -> basemapInfo(path(args.getString("path")))
        "basemap_plan_new" -> {
            val plan = longArrayOf(0)
            val created = outcome { plan[0] = planNew(args); null }
            if (plan[0] != 0L) NativeBridge.basemapPlanFree(plan[0])
            created
        }
        "basemap_bad_feed" -> basemapBadFeed(args)
        "basemap_extract" -> basemapExtract(args)
        else -> error("unknown op $op")
    }

    /** [PmtilesInfo.read]: the public type now carries every field of the C ABI object. */
    private fun basemapInfo(file: File): Map<String, Any?> = outcome {
        val info = PmtilesInfo.read(file)
        mapOf(
            "addressed_tiles" to info.addressedTiles,
            "bounds" to listOf(info.bounds.west, info.bounds.south, info.bounds.east, info.bounds.north),
            "center" to listOf(info.centerLon, info.centerLat, info.centerZoom),
            "clustered" to info.clustered,
            "file_bytes" to info.fileBytes,
            "max_zoom" to info.maxZoom,
            "min_zoom" to info.minZoom,
            "spec_version" to info.specVersion,
            "tile_compression" to info.tileCompression,
            "tile_contents" to info.tileContents,
            "tile_entries" to info.tileEntries,
            "tile_type" to info.tileType,
        )
    }

    // ---- basemap plan/assembler (internal NativeBridge; no public equivalent) ---------

    private fun planNew(args: JSONObject): Long {
        val bbox = args.get("bbox").let { if (it is String) it else bbox(it as JSONObject).toJson().toString() }
        return NativeBridge.basemapPlanNew(bbox, args.getInt("min_zoom"), args.getInt("max_zoom"), args.getDouble("overfetch"))
    }

    /** What an HTTP server answers to a Range request: the bytes that exist (short past the end). */
    private fun serve(source: ByteArray, offset: Long, length: Long): ByteArray {
        val start = offset.coerceAtMost(source.size.toLong()).toInt()
        val end = (offset + length).coerceAtMost(source.size.toLong()).toInt()
        return source.copyOfRange(start, end)
    }

    private fun long(map: Any?, key: String): Long = ((map as Map<*, *>)[key] as Long)

    private fun basemapBadFeed(args: JSONObject): Map<String, Any?> {
        val source = path(args.getString("source")).readBytes()
        val plan = NativeBridge.basemapPlanNew(
            bbox(args.getJSONObject("bbox")).toJson().toString(), args.getInt("min_zoom"), args.getInt("max_zoom"), args.getDouble("overfetch"),
        )
        try {
            val first = outcome { Canonical.parse(NativeBridge.basemapPlanFirstRequest(plan)) }
            val feeds = args.getJSONArray("feeds").let { list ->
                List(list.length()) {
                    val feed = list.getJSONObject(it)
                    val bytes = serve(source, feed.getLong("offset"), feed.getLong("length"))
                    outcome { Canonical.parse(NativeBridge.basemapPlanFeed(plan, feed.getLong("id"), bytes)) }
                }
            }
            return mapOf("first_request" to first, "feeds" to feeds)
        } finally {
            NativeBridge.basemapPlanFree(plan)
        }
    }

    private fun basemapExtract(args: JSONObject): Map<String, Any?> {
        val source = path(args.getString("source")).readBytes()
        val plan = planNew(args)
        var planOwned = true
        var assembler = 0L
        try {
            val first = outcome { Canonical.parse(NativeBridge.basemapPlanFirstRequest(plan)) }
            val queue = ArrayDeque<Any?>().apply { add((first["ok"])) }
            val feeds = ArrayList<Map<String, Any?>>()
            var ready = false
            // Plan phase: answer requests first in, first out until tiles_ready or an engine error.
            while (queue.isNotEmpty()) {
                val range = queue.removeFirst()
                val id = long(range, "id")
                val bytes = serve(source, long(range, "offset"), long(range, "length"))
                val step = outcome { Canonical.parse(NativeBridge.basemapPlanFeed(plan, id, bytes)) }
                feeds += mapOf("id" to id, "step" to step)
                val ok = step["ok"]
                if (ok is Map<*, *> && ok["fetch"] is List<*>) {
                    queue.addAll(ok["fetch"] as List<*>)
                } else if (ok is Map<*, *> && ok.containsKey("tiles_ready")) {
                    ready = true
                    break
                } else if (step.containsKey("error")) {
                    break
                } else {
                    assertEquals("unexpected step", "wait", ok)
                }
            }
            val outstanding = outcome { Canonical.parse(NativeBridge.basemapPlanOutstanding(plan)) }
            if (!ready) {
                val free = outcome { NativeBridge.basemapPlanFree(plan); planOwned = false; null }
                return mapOf("first_request" to first, "feeds" to feeds, "outstanding" to outstanding, "free" to free)
            }

            // Assembly phase. into_assembler consumes the plan whatever the outcome.
            val staging = File(scratch, "basemap.part")
            val output = File(scratch, "basemap.pmtiles")
            val into = outcome { planOwned = false; assembler = NativeBridge.basemapPlanIntoAssembler(plan, staging.path); null }
            assertEquals("into_assembler", mapOf("ok" to null), into)
            val remaining = outcome { Canonical.parse(NativeBridge.basemapAsmRemaining(assembler)) }
            val progressBefore = outcome { Canonical.parse(NativeBridge.basemapAsmProgress(assembler)) }
            // Finishing with ranges missing must be refused.
            val finishEarly = outcome { NativeBridge.basemapAsmFinish(assembler, output.path); null }
            val writes = (remaining["ok"] as List<*>).map { range ->
                val bytes = serve(source, long(range, "offset"), long(range, "length"))
                outcome { NativeBridge.basemapAsmWriteRange(assembler, long(range, "id"), bytes); null }
            }
            val progressAfter = outcome { Canonical.parse(NativeBridge.basemapAsmProgress(assembler)) }
            val finish = outcome { NativeBridge.basemapAsmFinish(assembler, output.path); null }
            val free = outcome { NativeBridge.basemapAsmFree(assembler); assembler = 0L; null }
            val info = basemapInfo(output)
            return mapOf(
                "first_request" to first,
                "feeds" to feeds,
                "outstanding" to outstanding,
                "into_assembler" to into,
                "remaining" to remaining,
                "progress_before" to progressBefore,
                "finish_early" to finishEarly,
                "writes" to writes,
                "progress_after" to progressAfter,
                "finish" to finish,
                "free" to free,
                "info" to info,
            )
        } finally {
            if (planOwned) runCatching { NativeBridge.basemapPlanFree(plan) }
            if (assembler != 0L) runCatching { NativeBridge.basemapAsmFree(assembler) }
        }
    }

    // ---- outcomes -----------------------------------------------------------------------

    /**
     * The canonical outcome of one call (README, "Outcomes"). A typed
     * [CantinoException] becomes `{"error":{"code","kind"}}`; the message is not
     * part of the outcome. [IllegalStateException] is how the JNI layer reports an
     * internal error (code 5). Anything else escapes as a harness error.
     */
    private fun outcome(missingOnNull: Boolean = false, block: () -> Any?): Map<String, Any?> = try {
        val value = block()
        if (value == null && missingOnNull) mapOf("missing" to true) else mapOf("ok" to value)
    } catch (e: CantinoException.InvalidArgument) {
        errorOutcome(1, "invalid_argument")
    } catch (e: CantinoException.InvalidFile) {
        errorOutcome(2, "invalid_file")
    } catch (e: CantinoException.Io) {
        errorOutcome(3, "io")
    } catch (e: CantinoException.WrongThread) {
        errorOutcome(4, "wrong_thread")
    } catch (e: IllegalStateException) {
        errorOutcome(5, "internal")
    }

    private fun errorOutcome(code: Int, kind: String): Map<String, Any?> = mapOf("error" to mapOf("code" to code, "kind" to kind))

    // ---- Kotlin values to canonical trees (the C ABI's JSON shapes) -------------------

    private fun tree(o: OsmObject): Map<String, Any?> {
        val common = mapOf(
            "id" to o.id.id,
            "tags" to o.tags,
            "type" to o.id.kind.wire,
            "metadata" to o.metadata?.let {
                mapOf("changeset" to it.changeset, "timestamp" to it.timestampSeconds, "uid" to it.uid, "user" to it.user, "version" to it.version)
            },
        )
        return common + when (o) {
            is OsmObject.Node -> mapOf(
                "coordinate" to mapOf("lat_e7" to o.latE7, "lon_e7" to o.lonE7),
                "location_version" to o.locationVersion,
            )
            is OsmObject.Way -> mapOf("nodes" to o.nodeIds)
            is OsmObject.Relation -> mapOf(
                "members" to o.members.map { mapOf("id" to mapOf("id" to it.id.id, "type" to it.id.kind.wire), "role" to it.role) },
            )
        }
    }

    // ---- JSON arguments to Kotlin values ------------------------------------------------

    private fun store(args: JSONObject): OsmStore = areas.getValue(args.getString("area"))

    private fun osmId(args: JSONObject): OsmId = OsmId(OsmKind.entries.first { it.code == args.getInt("kind") }, args.getLong("id"))

    private fun osmIdOf(json: JSONObject): OsmId = OsmId(OsmKind.fromWire(json.getString("type")), json.getLong("id"))

    private fun bbox(json: JSONObject): Bbox =
        Bbox(json.getDouble("west"), json.getDouble("south"), json.getDouble("east"), json.getDouble("north"))

    private fun baseOf(args: JSONObject): String? = if (args.isNull("base")) null else args.getString("base")

    private fun query(json: JSONObject): Query {
        val defaults = Query()
        val tags = json.optJSONArray("tags")?.let { list ->
            List(list.length()) {
                val filter = list.getJSONObject(it)
                when {
                    filter.has("Exists") -> TagFilter.Exists(filter.getString("Exists"))
                    filter.has("NotExists") -> TagFilter.NotExists(filter.getString("NotExists"))
                    else -> filter.getJSONArray("Equals").let { pair -> TagFilter.Equals(pair.getString(0), pair.getString(1)) }
                }
            }
        } ?: defaults.tags
        return Query(
            tags = tags,
            bbox = json.optJSONObject("bbox")?.let(::bbox),
            after = json.optJSONObject("after")?.let(::osmIdOf),
            limit = if (json.has("limit")) json.getInt("limit") else defaults.limit,
            maxCandidates = if (json.has("max_candidates")) json.getInt("max_candidates") else defaults.maxCandidates,
        )
    }

    // ---- files --------------------------------------------------------------------------

    private fun asset(name: String): ByteArray = context.assets.open(name).use { it.readBytes() }

    /**
     * `scratch:<name>` is inside the run's scratch directory; any other path is
     * repository-relative and bundled as an androidTest asset (tests/fixtures/x and
     * tests/parity/x as `x`, see build.gradle.kts), copied out on first use.
     */
    private fun path(name: String): File {
        if (name.startsWith("scratch:")) return File(scratch, name.removePrefix("scratch:"))
        val asset = when {
            name.startsWith("tests/fixtures/") -> name.removePrefix("tests/fixtures/")
            name.startsWith("tests/parity/") -> name.removePrefix("tests/parity/")
            else -> error("no asset mapping for $name")
        }
        return File(repo, name).also { file ->
            if (!file.exists()) {
                file.parentFile!!.mkdirs()
                file.writeBytes(asset(asset))
            }
        }
    }

    // ---- result file --------------------------------------------------------------------

    /** `{"id":"x","result":...}` lines of expected.json keyed by id (trailing comma dropped). */
    private fun expectedLines(text: String): Map<String, String> {
        val lines = text.split("\n").filter { it.startsWith("{\"id\":") }.map { it.removeSuffix(",") }
        return lines.associateBy { JSONObject(it).getString("id") }.also { assertEquals(lines.size, it.size) }
    }

    private fun resultFile(lines: List<String>): String = "[\n" + lines.joinToString(",\n") + "\n]\n"

    private companion object {
        const val TAG = "ParityTest"
    }
}
