{
  "formatVersion": "1.1",
  "component": {
    "group": "io.github.mvexel",
    "module": "cantino",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "cantino-0.1.0.aar",
          "url": "cantino-0.1.0.aar",
          "size": 3509887,
          "sha512": "440255175c6e19e23f60c552b8f8423f4a9b5e074bfeac59c1d82e8e08fec6c65163c62d659a99eb8a0ed9616c193b347f5e0807088c290f01644149e17403c7",
          "sha256": "5f22fc1f5596dc97cdc012a974a11f6e7545029d2216f3107b183d31ae0660a7",
          "sha1": "e9b41cb539f5d18971934ed93ba0d06dc82ca00b",
          "md5": "3110ad22902163ae6ded314c40b54797"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "cantino-0.1.0.aar",
          "url": "cantino-0.1.0.aar",
          "size": 3509887,
          "sha512": "440255175c6e19e23f60c552b8f8423f4a9b5e074bfeac59c1d82e8e08fec6c65163c62d659a99eb8a0ed9616c193b347f5e0807088c290f01644149e17403c7",
          "sha256": "5f22fc1f5596dc97cdc012a974a11f6e7545029d2216f3107b183d31ae0660a7",
          "sha1": "e9b41cb539f5d18971934ed93ba0d06dc82ca00b",
          "md5": "3110ad22902163ae6ded314c40b54797"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cantino-0.1.0-sources.jar",
          "url": "cantino-0.1.0-sources.jar",
          "size": 46870,
          "sha512": "4b44026da8a8e0323bf39d9da0feb5e66fe2df3fff280a60b61ed44f1a2528dbbbb102d01945e69dd82691c578a50e89554fd5403645dc47b2b91fd1ad8efdff",
          "sha256": "b333db6023954c43ecd0452e103ef8d6659b1cdfcf7a8bb48598bc4cc4e2cfd2",
          "sha1": "19c104ad868629efd489cdcf48914b22afebe364",
          "md5": "b5b4a0fe75dfb07c1c5ba2b6aee68dae"
        }
      ]
    }
  ]
}
