{
  "formatVersion": "1.1",
  "component": {
    "group": "lol.osm",
    "module": "cantino",
    "version": "0.4.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.8.0"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "cantino-0.4.0.aar",
          "url": "cantino-0.4.0.aar",
          "size": 3725585,
          "sha512": "d488c0a19790d5e86ec943f0b273b225d6a4ed666f45a9f64f4d7c60c4efa3f8794a664fbc58e33d6987897a6496623f9248295a971daa4b87b59f29bd7ebf56",
          "sha256": "a2780fddb3a9539d1c10458323937628fd279e1448c3f5ce43055f784809d8d7",
          "sha1": "e5cf51e5abf15990336de1984a05ee4c1e2cfd10",
          "md5": "d79854f0444f2443d17801e083c65163"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.12.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.10"
          }
        }
      ],
      "files": [
        {
          "name": "cantino-0.4.0.aar",
          "url": "cantino-0.4.0.aar",
          "size": 3725585,
          "sha512": "d488c0a19790d5e86ec943f0b273b225d6a4ed666f45a9f64f4d7c60c4efa3f8794a664fbc58e33d6987897a6496623f9248295a971daa4b87b59f29bd7ebf56",
          "sha256": "a2780fddb3a9539d1c10458323937628fd279e1448c3f5ce43055f784809d8d7",
          "sha1": "e5cf51e5abf15990336de1984a05ee4c1e2cfd10",
          "md5": "d79854f0444f2443d17801e083c65163"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "cantino-0.4.0-sources.jar",
          "url": "cantino-0.4.0-sources.jar",
          "size": 55052,
          "sha512": "502453d61f7f3d59a2d28eb45fe862dfa68c8d672880243575cf8b8025eb5637372805287b3e4b3f35532223866d5fb6e948500f220a5ff51e4325490a28c859",
          "sha256": "24813c4284fd577d881fbe8d273802372a5295368021a4a369122591e632eccb",
          "sha1": "26405c17b2af727665f167e4867d3e509a3feb71",
          "md5": "1eaf27c2039bfb09d6a509058a1fbbfd"
        }
      ]
    }
  ]
}
