#!/bin/sh
# (Re)creates the offline basemap assets for android/sample-app from scratch:
#   build-assets/slc.pmtiles            Protomaps v4 extract of the SLC bbox, z0-15
#   build-assets/style.json             Protomaps "light" flavor, source url placeholder
#   build-assets/glyphs/<stack>/*.pbf   Noto Sans stacks, Latin ranges only
#   build-assets/sprites/light{,@2x}.{json,png}
# Large inputs are cached in work/basemap (gitignored) and reused when present,
# so the repo itself never carries binaries. Delete work/basemap to refetch.
# Needs: curl, tar, git, node/npm (only when the style must be regenerated).
set -eu
root=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
cache="${BASEMAP_CACHE:-$root/work/basemap}"  # override to test a cold run
out="$root/android/sample-app/build-assets"

pmtiles_version=1.31.2
planet_build=https://build.protomaps.com/20261002.pmtiles
bbox=-112.10,40.70,-111.80,40.85
maxzoom=15
basemaps_version=5.7.2
# MapLibre requests glyphs in 256-codepoint ranges. Keep Basic Latin, Latin-1,
# Latin Extended-A/B, IPA/spacing modifiers, combining diacritics + Greek,
# Cyrillic (an SLC label requested it, 2026-10-03) and general
# punctuation (dashes, curly quotes). Labels are English (lang: "en"); glyphs
# outside these ranges simply fail to load and are logged by MapLibre.
ranges="0-255 256-511 512-767 768-1023 1024-1279 8192-8447"
stacks="Noto Sans Regular|Noto Sans Medium|Noto Sans Italic"

mkdir -p "$cache"
rm -rf "$out"
mkdir -p "$out/glyphs" "$out/sprites"

# 1. pmtiles CLI (go-pmtiles), pinned.
if [ ! -x "$cache/pmtiles" ]; then
    case "$(uname -s)-$(uname -m)" in
        Linux-x86_64) asset="go-pmtiles_${pmtiles_version}_Linux_x86_64.tar.gz" ;;
        Linux-aarch64) asset="go-pmtiles_${pmtiles_version}_Linux_arm64.tar.gz" ;;
        Darwin-arm64) asset="go-pmtiles-${pmtiles_version}_Darwin_arm64.zip" ;;
        Darwin-x86_64) asset="go-pmtiles-${pmtiles_version}_Darwin_x86_64.zip" ;;
        *) echo "unsupported host $(uname -s)-$(uname -m)" >&2; exit 2 ;;
    esac
    url="https://github.com/protomaps/go-pmtiles/releases/download/v${pmtiles_version}/$asset"
    tmp=$(mktemp -d)
    curl -fsSL -o "$tmp/$asset" "$url"
    case "$asset" in
        *.zip) (cd "$tmp" && unzip -q "$asset") ;;
        *) tar -xzf "$tmp/$asset" -C "$tmp" ;;
    esac
    mv "$tmp/pmtiles" "$cache/pmtiles"
    rm -rf "$tmp"
fi

# 2. Basemap extract: range-reads only the needed tiles from the planet build.
if [ ! -s "$cache/slc.pmtiles" ]; then
    "$cache/pmtiles" extract "$planet_build" "$cache/slc.pmtiles.part" \
        --bbox="$bbox" --maxzoom="$maxzoom"
    mv "$cache/slc.pmtiles.part" "$cache/slc.pmtiles"
fi
cp "$cache/slc.pmtiles" "$out/slc.pmtiles"

# 3. Fonts and sprites: sparse, blobless clone of protomaps/basemaps-assets.
if [ ! -d "$cache/basemaps-assets/sprites/v4" ]; then
    rm -rf "$cache/basemaps-assets"
    git clone -q --filter=blob:none --sparse --depth 1 \
        https://github.com/protomaps/basemaps-assets "$cache/basemaps-assets"
    git -C "$cache/basemaps-assets" sparse-checkout set --no-cone \
        "/fonts/Noto Sans Regular/" "/fonts/Noto Sans Medium/" \
        "/fonts/Noto Sans Italic/" /fonts/OFL.txt /sprites/v4/
fi
IFS='|'
for stack in $stacks; do
    mkdir -p "$out/glyphs/$stack"
    IFS=' '
    for r in $ranges; do
        cp "$cache/basemaps-assets/fonts/$stack/$r.pbf" "$out/glyphs/$stack/"
    done
    IFS='|'
done
IFS=' '
cp "$cache/basemaps-assets/fonts/OFL.txt" "$out/glyphs/"
for f in light.json light.png light@2x.json light@2x.png; do
    cp "$cache/basemaps-assets/sprites/v4/$f" "$out/sprites/"
done

# 4. Style: generated by @protomaps/basemaps so layers match the v4 tiles.
if [ ! -s "$cache/style.json" ]; then
    cat > "$cache/make-style.js" <<'EOF'
// Offline Protomaps light style for MapLibre Native. The PMTiles URL is a
// placeholder the app replaces with its runtime file path.
const { layers, namedFlavor } = require("@protomaps/basemaps");
const style = {
  version: 8,
  glyphs: "asset://glyphs/{fontstack}/{range}.pbf",
  sprite: "asset://sprites/light",
  sources: {
    protomaps: { type: "vector", url: "__PMTILES_URL__", attribution: "© OpenStreetMap contributors, Protomaps" },
  },
  layers: layers("protomaps", namedFlavor("light"), { lang: "en" }),
};
require("fs").writeFileSync("style.json", JSON.stringify(style));
EOF
    (cd "$cache" && npm install --silent --no-save "@protomaps/basemaps@$basemaps_version" \
        && node make-style.js)
fi
cp "$cache/style.json" "$out/style.json"

du -sh "$out"/* | sed "s|$out|build-assets|"
du -sh "$out" | sed "s|$out|build-assets (total)|"
