// Offline basemap sample: renders a PMTiles extract with MapLibre Native and
// no network. Assets are generated by ../../scripts/basemap-assets.sh into
// build-assets/ (gitignored) so the repo carries no large binaries.
plugins {
    id("com.android.application")
}

android {
    namespace = "io.github.mvexel.cantino.sample"
    compileSdk = 36
    defaultConfig {
        applicationId = "io.github.mvexel.cantino.sample"
        minSdk = 26
        targetSdk = 36
        versionCode = 1
        versionName = "0.1.0"
        // Same ABIs the framework AAR ships: phones and x86_64 emulators.
        ndk { abiFilters += listOf("arm64-v8a", "armeabi-v7a", "x86_64") }
    }
    sourceSets {
        getByName("main").assets.directories.add("build-assets")
    }
    androidResources {
        // Stored uncompressed so the first-launch copy can compare lengths
        // through openFd() (and the tiles inside are gzipped already).
        noCompress += "pmtiles"
    }
}

// Fail early with a pointer to the generator instead of shipping an app with
// an empty map.
val checkBasemapAssets by tasks.registering {
    val style = layout.projectDirectory.file("build-assets/style.json").asFile
    doLast {
        check(style.exists()) { "missing $style; run scripts/basemap-assets.sh first" }
    }
}
tasks.named("preBuild") { dependsOn(checkBasemapAssets) }

dependencies {
    // Linked only; the café features that use it come in phase 6.
    implementation(project(":cantino"))
    implementation("org.maplibre.gl:android-sdk:13.6.1")
}
